### ISSUE TITLE
Could not load assembly 'crypto, Version=1.8.0.0.

### ISSUE THREAD

**Issue by imzuhdi** [AArnott/PCLCrypto#140]
I get this error :

Severity	Code	Description	Project	File	Line	Suppression State
Error		Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'crypto, Version=1.8.0.0, Culture=neutral, PublicKeyToken=0e99375e54769942'. Perhaps it doesn't exist in the Mono for Android profile?
File name: 'crypto.dll'
   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters) in /Users/builder/data/lanes/5749/9cfa7836/source/xamarin-android/external/Java.Interop/src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil/DirectoryAssemblyResolver.cs:line 229
   at Xamarin.Android.Tasks.ResolveAssemblies.AddAssemblyReferences(DirectoryAssemblyResolver resolver, ICollection`1 assemblies, AssemblyDefinition assembly, Boolean topLevel)
   at Xamarin.Android.Tasks.ResolveAssemblies.Execute(DirectoryAssemblyResolver resolver)	Cross.Android

**Comment by AArnott** [comment]
I've never seen this. PCLCrypto doesn't have a reference on any `crypto` assembly, so I can only imagine mono or xamarin is _supposed_ to deploy this and didn't.

What version of PCLCrypto were you using when you saw this?
