### ISSUE TITLE
Exception while building in Xamarin.Android project with latest version

### ISSUE THREAD

**Issue by jesusgarza** [AArnott/PCLCrypto#84]
While building a Xamarin.Android project I get this:

`Error       Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'CodeGeneration.Roslyn.Attributes, Version=0.1.0.0, Culture=neutral, PublicKeyToken=ec41cf4c17a5eaf3'. Perhaps it doesn't exist in the Mono for Android profile?
File name: 'CodeGeneration.Roslyn.Attributes.dll'
   at Xamarin.Android.Tuner.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters)
   at Xamarin.Android.Tasks.ResolveAssemblies.AddAssemblyReferences(ICollection 1 assemblies, AssemblyDefinition assembly, Boolean topLevel)
   at Xamarin.Android.Tasks.ResolveAssemblies.Execute() Sensor`

I tried uninstalling only PCLCrypto and leave the PInvoke.* dependencies, but I still get the same error.

I removed PCLCrypto latest version with all dependencies, installed version 1.0.86 and that solved it. More people are reporting this: https://forums.xamarin.com/discussion/63419/exception-while-loading-assemblies-issue

**Comment by AArnott** [comment]
I can repro this with 2.0.144
